#!/usr/bin/env python3
"""
Agentic Control Kernel — Bootstrap Script

Installs control-kernel primitives into a target repository:
  - .control/ directory (policy.yaml, plant.yaml)
  - schemas/ directory (state, action, trace, evaluator JSON schemas)
  - METALAYER.md with control-kernel sections
  - Harness gates wired to make targets

Usage:
    python3 control_kernel_init.py <repo-path> [--profile baseline|governed|autonomous] [--runtime subprocess|arcan] [--ledger file|lago] [--force]
"""

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = SKILL_ROOT / "assets" / "templates"
SCHEMAS_DIR = SKILL_ROOT / "schemas"

PROFILES = ["baseline", "governed", "autonomous"]
RUNTIMES = ["subprocess", "arcan"]
LEDGERS = ["file", "lago"]

RUNTIME_CONFIG_TEMPLATE = """\
# Runtime integration — generated by agentic-control-kernel
# Runtime: {runtime} | Ledger: {ledger}

runtime:
  kind: {runtime}
{runtime_block}
ledger:
  kind: {ledger}
{ledger_block}
"""

ARCAN_RUNTIME_BLOCK = """\
  base_url: "http://localhost:3000"
  policy:
    allow_capabilities: ["fs:read:**", "fs:write:**", "exec:*"]
"""

LAGO_LEDGER_BLOCK = """\
  base_url: "http://localhost:3001"
  event_prefix: "egri."
"""

METALAYER_TEMPLATE = """\
# Metalayer — Agentic Control Kernel

> Generated by agentic-control-kernel on {timestamp}
> Profile: {profile}

## Control Loop Definition

```
Plant → observe() → Runtime → update estimator → b_t
  → LLM Agent: decision(b_t) → θ_t (typed control directive)
  → Controller: propose(b_t, θ_t) → proposed u_t
  → Safety Shield: filter(u_t, b_t) → safe u_t + certificate
  → Plant: apply(safe u_t) → result
  → Evaluator/Ledger: append trace + score
```

## Setpoints

| ID | Metric | Target | Alert | Severity |
|----|--------|--------|-------|----------|
| S1 | gate_pass_rate | 0.85 | <0.70 | blocking |
| S2 | audit_pass_rate | 1.0 | <0.95 | blocking |
| S3 | constraint_violation_rate | 0.0 | >0.0 | blocking |
| S4 | shield_intervention_rate | 0.0 | >0.05 | info |
| S5 | shield_feasibility_rate | 1.0 | <0.99 | blocking |

## Sensors

- `make smoke` — environment/build sanity
- `make check` — lint + typecheck
- `make test` — full verification suite
- `make control-audit` — metalayer artifact validation

## Controller Policy

See `.control/policy.yaml` for full gate definitions.

### Hard Gates
- G1: LLM must not call Plant directly
- G2: Safety shield must not be bypassed
- G3: Constraint violations halt execution
- G4: Evaluator and artifact not mutated in same trial

## Plant Interface

See `.control/plant.yaml` for typed state/action definitions.

## Feedback Loop

1. Run `smoke` → if fail, stop and fix
2. Run `check` → if fail, block merge
3. Run `test` → if fail, bounded retries then escalate
4. Run `control-audit` → if fail, review metalayer artifacts
5. Persistent failures → tighten policy or reduce mutation surface

## Multi-Rate Hierarchy

| Loop | Cadence | LLM? | Responsibility |
|------|---------|------|----------------|
| Inner | ms | No | Deterministic controllers, CBF-QP |
| Mid | 10-100ms | Params only | MPC planning, estimator resets |
| Outer | seconds | Yes | Goal setting, mode switching |
| Meta (EGRI) | min-days | Yes | Controller synthesis, model learning |
"""


def copy_template(src: Path, dst: Path, force: bool = False) -> bool:
    """Copy a template file, respecting --force flag."""
    if dst.exists() and not force:
        print(f"  [skip] {dst.relative_to(dst.parent.parent)} (exists, use --force)")
        return False
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    print(f"  [ok]   {dst.relative_to(dst.parent.parent)}")
    return True


def install_schemas(repo: Path, force: bool = False) -> int:
    """Install JSON schemas into repo/schemas/."""
    installed = 0
    schemas_dst = repo / "schemas"
    schemas_dst.mkdir(parents=True, exist_ok=True)

    for schema_file in sorted(SCHEMAS_DIR.glob("*.json")):
        dst = schemas_dst / schema_file.name
        if copy_template(schema_file, dst, force):
            installed += 1
    return installed


def install_control(repo: Path, profile: str, force: bool = False) -> int:
    """Install .control/ templates."""
    installed = 0
    control_src = TEMPLATES_DIR / ".control"

    for tmpl in sorted(control_src.glob("*.yaml")):
        dst = repo / ".control" / tmpl.name
        if copy_template(tmpl, dst, force):
            installed += 1

    # Update profile in policy.yaml
    policy_path = repo / ".control" / "policy.yaml"
    if policy_path.exists():
        content = policy_path.read_text()
        content = content.replace("profile: governed", f"profile: {profile}")
        policy_path.write_text(content)

    return installed


def install_metalayer(repo: Path, profile: str, force: bool = False) -> int:
    """Generate METALAYER.md."""
    dst = repo / "METALAYER.md"
    if dst.exists() and not force:
        print(f"  [skip] METALAYER.md (exists, use --force)")
        return 0

    content = METALAYER_TEMPLATE.format(
        timestamp=datetime.now(timezone.utc).isoformat(),
        profile=profile,
    )
    dst.write_text(content)
    print(f"  [ok]   METALAYER.md")
    return 1


def install_runtime_config(
    repo: Path, runtime: str, ledger: str, force: bool = False
) -> int:
    """Generate .control/runtime.yaml with Arcan/Lago integration points."""
    dst = repo / ".control" / "runtime.yaml"
    if dst.exists() and not force:
        print(f"  [skip] .control/runtime.yaml (exists, use --force)")
        return 0

    runtime_block = ARCAN_RUNTIME_BLOCK if runtime == "arcan" else "  # default subprocess — no extra config\n"
    ledger_block = LAGO_LEDGER_BLOCK if ledger == "lago" else "  # default file ledger — writes to ledger.jsonl\n"

    content = RUNTIME_CONFIG_TEMPLATE.format(
        runtime=runtime,
        ledger=ledger,
        runtime_block=runtime_block,
        ledger_block=ledger_block,
    )
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(content)
    print(f"  [ok]   .control/runtime.yaml")
    return 1


def install_problem_spec(repo: Path, force: bool = False) -> int:
    """Install EGRI problem-spec template."""
    src = TEMPLATES_DIR / "problem-spec.control.yaml"
    dst = repo / "problem-spec.control.yaml"
    return 1 if copy_template(src, dst, force) else 0


def main():
    parser = argparse.ArgumentParser(
        description="Bootstrap agentic control kernel into a repository"
    )
    parser.add_argument("repo_path", type=Path, help="Target repository path")
    parser.add_argument(
        "--profile",
        choices=PROFILES,
        default="governed",
        help="Control profile (default: governed)",
    )
    parser.add_argument(
        "--runtime",
        choices=RUNTIMES,
        default="subprocess",
        help="Agent runtime backend (default: subprocess)",
    )
    parser.add_argument(
        "--ledger",
        choices=LEDGERS,
        default="file",
        help="Ledger backend for traces/EGRI events (default: file)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files",
    )

    args = parser.parse_args()
    repo = args.repo_path.resolve()

    if not repo.is_dir():
        print(f"Error: {repo} is not a directory", file=sys.stderr)
        sys.exit(1)

    print(f"\nAgentic Control Kernel — Bootstrap")
    print(f"  Target:  {repo}")
    print(f"  Profile: {args.profile}")
    print(f"  Runtime: {args.runtime}")
    print(f"  Ledger:  {args.ledger}")
    print()

    total = 0

    print("Installing schemas...")
    total += install_schemas(repo, args.force)

    print("\nInstalling .control/ primitives...")
    total += install_control(repo, args.profile, args.force)

    print("\nConfiguring runtime integration...")
    total += install_runtime_config(repo, args.runtime, args.ledger, args.force)

    print("\nGenerating METALAYER.md...")
    total += install_metalayer(repo, args.profile, args.force)

    print("\nInstalling EGRI problem-spec template...")
    total += install_problem_spec(repo, args.force)

    print(f"\nDone. {total} files installed.")
    print(f"\nNext steps:")
    print(f"  1. Edit .control/plant.yaml — define your plant's state and actions")
    print(f"  2. Edit .control/policy.yaml — customize setpoints and gates")
    if args.runtime == "arcan":
        print(f"  3. Ensure Arcan is running at the configured base_url")
    if args.ledger == "lago":
        print(f"  4. Ensure Lago is running at the configured base_url")
    print(f"  5. Run: make smoke && make control-audit")
    print(f"  6. See SKILL.md references for architecture and safety patterns")

    result = {
        "status": "ok",
        "repo": str(repo),
        "profile": args.profile,
        "runtime": args.runtime,
        "ledger": args.ledger,
        "files_installed": total,
    }
    print(f"\n{json.dumps(result)}")


if __name__ == "__main__":
    main()
