"""Unit tests for resume_corpus_stats — the script that regenerates SKILL.md's numbers.

SKILL.md argues from measured statistics. A number in prose and a number from a
sweep render identically, so the claim is worth exactly as much as this script.
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
import resume_corpus_stats as rcs  # noqa: E402


def assistant(*blocks, **kw):
    return dict(type="assistant", message={"content": list(blocks)}, **kw)


def user_turn(text, **kw):
    return dict(type="user", message={"content": [{"type": "text", "text": text}]}, **kw)


def tool_result(tid, content):
    return dict(type="user", message={"content": [
        {"type": "tool_result", "tool_use_id": tid, "content": content}]})


def spawn(tid="t1", name="Agent"):
    return {"type": "tool_use", "id": tid, "name": name,
            "input": {"description": "d", "prompt": "p"}}


def write(tmp_path, records, name="s.jsonl"):
    p = tmp_path / name
    p.write_text("\n".join(json.dumps(r) for r in records), encoding="utf-8")
    return str(p)


# ---------------------------------------------------------------- detection

def test_bare_resume_is_counted(tmp_path):
    hits = rcs.analyse_file(write(tmp_path, [user_turn("resume")]))
    assert len(hits) == 1
    assert hits[0]["text"] == "resume"


def test_continuation_forms_counted(tmp_path):
    for form in ["continue", "carry on", "keep going", "pick up where you left off",
                 "please resume", "continue /autonomous"]:
        hits = rcs.analyse_file(write(tmp_path, [user_turn(form)], name=f"{abs(hash(form))}.jsonl"))
        assert len(hits) == 1, f"missed {form!r}"


def test_long_turn_is_not_a_resume(tmp_path):
    """A resume turn is terse. A long instruction that opens with 'continue'
    is a work request, not a restoration command."""
    long = "continue " + ("x" * 200)
    assert rcs.analyse_file(write(tmp_path, [user_turn(long)])) == []


def test_harness_injections_are_not_human_turns(tmp_path):
    recs = [user_turn("resume <system-reminder>injected</system-reminder>"),
            user_turn("Caveat: resume was generated by a local command")]
    assert rcs.analyse_file(write(tmp_path, recs)) == []


def test_sidechain_turns_excluded(tmp_path):
    recs = [dict(type="user", isSidechain=True,
                 message={"content": [{"type": "text", "text": "resume"}]})]
    assert rcs.analyse_file(write(tmp_path, recs)) == []


def test_unrelated_prompt_not_counted(tmp_path):
    assert rcs.analyse_file(write(tmp_path, [user_turn("what does this function do?")])) == []


# ------------------------------------------------------------ preceded-by

def test_api_error_before_resume_detected(tmp_path):
    recs = [assistant({"type": "text", "text": "API Error: 529 Overloaded"}),
            user_turn("resume")]
    assert "api_error" in rcs.analyse_file(write(tmp_path, recs))[0]["preceded_by"]


def test_interrupt_before_resume_detected(tmp_path):
    recs = [user_turn("[Request interrupted by user]"), user_turn("resume")]
    assert "interrupt" in rcs.analyse_file(write(tmp_path, recs))[0]["preceded_by"]


def test_clean_resume_has_no_precedent(tmp_path):
    recs = [assistant({"type": "text", "text": "done"}), user_turn("resume")]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["preceded_by"] == []


# --------------------------------------------------------------- in flight

def test_inflight_spawn_counted(tmp_path):
    recs = [assistant(spawn("t1")), assistant(spawn("t2")), user_turn("resume")]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["inflight_spawns"] == 2


# ------------------------------------------------------------ what happened

def test_respawn_after_resume_detected(tmp_path):
    recs = [user_turn("resume"), assistant(spawn("t9"))]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["respawned"] is True


def test_no_tools_after_resume_detected(tmp_path):
    """The measured dominant failure: a text-only wrap-up."""
    recs = [user_turn("resume"),
            assistant({"type": "text", "text": "Here is where things stand."})]
    h = rcs.analyse_file(write(tmp_path, recs))[0]
    assert h["no_tools"] is True and h["respawned"] is False


def test_queried_running_tasks_detected(tmp_path):
    recs = [user_turn("resume"),
            assistant({"type": "tool_use", "id": "x", "name": "TaskOutput", "input": {}})]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["queried_tasks"] is True


def test_death_acknowledged_without_restore(tmp_path):
    recs = [user_turn("resume"),
            assistant({"type": "text", "text": "Three sub-agents died mid-flight; noting the gap."})]
    h = rcs.analyse_file(write(tmp_path, recs))[0]
    assert h["acknowledged_death"] is True and h["respawned"] is False


def test_analysis_stops_at_the_next_human_turn(tmp_path):
    """Work after the operator speaks again belongs to that turn, not this one."""
    recs = [user_turn("resume"),
            assistant({"type": "text", "text": "ok"}),
            user_turn("now do something else"),
            assistant(spawn("t5"))]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["respawned"] is False


def test_retyped_resume_detected(tmp_path):
    recs = [user_turn("resume"),
            assistant({"type": "text", "text": "summary"}),
            user_turn("resume")]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["retyped"] is True


def test_retyped_false_when_next_turn_is_new_work(tmp_path):
    recs = [user_turn("resume"),
            assistant({"type": "text", "text": "summary"}),
            user_turn("add a test for the parser please")]
    assert rcs.analyse_file(write(tmp_path, recs))[0]["retyped"] is False


# ----------------------------------------------------------------- summary

def test_summary_counts(tmp_path):
    hits = [
        {"text": "resume", "preceded_by": ["api_error"], "inflight_spawns": 1,
         "respawned": False, "queried_tasks": False, "no_tools": True,
         "acknowledged_death": True, "retyped": True},
        {"text": "carry on", "preceded_by": [], "inflight_spawns": 0,
         "respawned": True, "queried_tasks": False, "no_tools": False,
         "acknowledged_death": True, "retyped": False},
    ]
    s = rcs.summarise(hits, files=7)
    assert s["files_scanned"] == 7
    assert s["resume_turns"] == 2
    assert s["bare_resume"] == 1
    assert s["preceded_by_api_error"] == 1
    assert s["had_inflight_spawn"] == 1
    assert s["no_tool_calls_at_all"] == 1
    assert s["acknowledged_death_not_restored"] == 1
    assert s["acknowledged_death_and_restored"] == 1
    assert s["retyped_within_40_records"] == 1
    assert s["distinct_surface_forms"] == 2


def test_render_contains_every_headline_row(tmp_path):
    out = rcs.render(rcs.summarise([], files=0))
    for label in ["resume-class turns", "preceded by an API error",
                  "had a spawn IN FLIGHT", "NO tool calls at all",
                  "resume retyped"]:
        assert label in out


# ------------------------------------------------------------------ robust

def test_malformed_lines_are_skipped_not_fatal(tmp_path):
    p = tmp_path / "bad.jsonl"
    p.write_text('{"broken\n' + json.dumps(user_turn("resume")), encoding="utf-8")
    assert len(rcs.analyse_file(str(p))) == 1


def test_missing_file_returns_empty():
    assert rcs.analyse_file("/nonexistent/x.jsonl") == []


def test_main_exits_2_without_corpus(tmp_path):
    assert rcs.main(["--root", str(tmp_path / "absent")]) == 2


def test_main_json(tmp_path, capsys):
    write(tmp_path, [user_turn("resume")])
    assert rcs.main(["--root", str(tmp_path), "--json"]) == 0
    assert json.loads(capsys.readouterr().out)["resume_turns"] == 1
