"""Tests for scripts/publish_check.py — what must never leave the machine."""
from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "publish_check.py"
spec = importlib.util.spec_from_file_location("publish_check", SCRIPT)
pc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pc)


def kinds(root: Path, **kw) -> set[tuple[str, str]]:
    kw.setdefault("hostnames", set())
    kw.setdefault("username", None)
    return {(f["kind"], f["path"]) for f in pc.scan(root, **kw)}


@pytest.fixture
def clean(tmp_path: Path) -> Path:
    (tmp_path / "main.js").write_text("module.exports = class Plugin {}\n")
    (tmp_path / "manifest.json").write_text('{"id": "x"}\n')
    (tmp_path / "README.md").write_text("Install into <vault>/.obsidian/plugins/x\n")
    return tmp_path


def test_clean_mod_passes(clean: Path):
    assert pc.scan(clean) == []
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 0 and r.stdout.startswith("OK")


@pytest.mark.parametrize("name", ["app.asar", "libfoo.dylib", "game.z64", "data.pak"])
def test_third_party_binaries_block(clean: Path, name: str):
    (clean / name).write_bytes(b"\x00\x01")
    assert ("binary", name) in kinds(clean)


def test_app_bundle_directory_blocks_and_is_not_descended(clean: Path):
    (clean / "Target.app" / "Contents").mkdir(parents=True)
    (clean / "Target.app" / "Contents" / "x.dylib").write_bytes(b"\x00")
    found = kinds(clean)
    assert ("binary", "Target.app") in found
    assert not any(p.startswith("Target.app/") for _, p in found)


def test_allow_glob_exempts(clean: Path):
    (clean / "assets").mkdir()
    (clean / "assets" / "own.bin").write_bytes(b"\x00")
    assert ("binary", "assets/own.bin") in kinds(clean)
    assert ("binary", "assets/own.bin") not in kinds(clean, allow=["assets/*.bin"])


def test_large_file_blocks(clean: Path):
    (clean / "big.txt").write_bytes(b"a" * (2 * 1024 * 1024))
    assert ("large", "big.txt") in kinds(clean, max_mb=1)
    assert ("large", "big.txt") not in kinds(clean, max_mb=5)


@pytest.mark.parametrize("text", [
    "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n",
    "key = AKIA" + "ABCDEFGHIJKLMNOP\n",
    "token: ghp_" + "a" * 36 + "\n",
    "SLACK=xoxb-" + "1234567890-abcdef\n",
    "OPENAI=sk-" + "a" * 24 + "\n",
])
def test_secrets_block(clean: Path, text: str):
    (clean / "config.js").write_text(text)
    assert ("secret", "config.js") in kinds(clean)


@pytest.mark.parametrize("header", [
    "// Decompiled with JetBrains decompiler\n",
    "// Generated by Ghidra\n",
    "/* jadx */\n",
    "// ILSpy output\n",
])
def test_decompiler_output_blocks(clean: Path, header: str):
    (clean / "Lifted.java").write_text(header + "class A {}\n")
    assert ("decomp", "Lifted.java") in kinds(clean)


@pytest.mark.parametrize("text,blocks", [
    ("path = '/Users/alice/Library/x'", True),
    ("path = '/home/bob/.config'", True),
    (r"path = 'C:\Users\carol\AppData'", True),
    ("path = '/Users/Shared/x'", False),
    ("path = '~/Library/x'", False),
])
def test_user_paths(clean: Path, text: str, blocks: bool):
    (clean / "paths.py").write_text(text + "\n")
    assert (("userpath", "paths.py") in kinds(clean)) is blocks


def test_skips_vcs_and_dependency_dirs(clean: Path):
    (clean / "node_modules" / "dep").mkdir(parents=True)
    (clean / "node_modules" / "dep" / "lib.dylib").write_bytes(b"\x00")
    (clean / ".git").mkdir()
    (clean / ".git" / "secret").write_text("ghp_" + "a" * 36)
    assert pc.scan(clean) == []


def test_binary_content_is_strings_scanned(clean: Path):
    # An image's metadata can carry a path; the scan reads printable runs of binary files.
    (clean / "icon.png").write_bytes(b"\x89PNG\x00" + b"/Users/alice/" )
    assert ("userpath", "icon.png") in kinds(clean)


def test_cli_exit_codes(clean: Path, tmp_path: Path):
    (clean / "x.dll").write_bytes(b"\x00")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK binary" in r.stdout
    r = subprocess.run([sys.executable, str(SCRIPT), str(tmp_path / "nope")], capture_output=True, text=True)
    assert r.returncode == 2


# --- added after the first dogfood run (BRO-2816 friction report) -------------------

@pytest.mark.parametrize("text", [
    "lock: Janes-MacBook-Pro.local-52658",
    "host=Bob-Mac-mini.local",
    "SingletonLock -> Ana-MacBook-Air-2",
])
def test_mac_style_hostnames_block(clean: Path, text: str):
    (clean / "lab.log").write_text(text + "\n")
    assert ("hostname", "lab.log") in kinds(clean, hostnames=set())


def test_this_machines_hostname_blocks(clean: Path):
    (clean / "lab.log").write_text("pid 4242 on studio-workstation-7\n")
    assert ("hostname", "lab.log") in kinds(clean, hostnames={"studio-workstation-7"})
    assert ("hostname", "lab.log") not in kinds(clean, hostnames=set())


def test_short_generic_hostnames_are_not_matched():
    assert all(len(h) >= 6 for h in pc.local_hostnames())
    assert "localhost" not in pc.local_hostnames()


def test_images_are_listed_for_review_not_blocked(clean: Path):
    (clean / "evidence").mkdir()
    (clean / "evidence" / "shot.png").write_bytes(b"\x89PNG\x00")
    assert pc.scan(clean, hostnames=set(), username=None) == []
    assert pc.review_images(clean) == ["evidence/shot.png"]
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 0 and "REVIEW image    evidence/shot.png" in r.stdout


# --- added after P20 round 1 (BRO-2816) ---------------------------------------------

import os
import stat as _stat


def test_symlinked_file_and_dir_are_findings_with_their_target(clean: Path, tmp_path: Path):
    (clean / "secret.txt").write_text("nothing\n")
    os.symlink("../outside/key", clean / "key")
    os.symlink("/Users/alice/.ssh", clean / "sshdir")
    found = pc.scan(clean, hostnames=set(), username=None)
    by = {f["path"]: f for f in found}
    assert by["key"]["kind"] == "symlink" and "../outside/key" in by["key"]["detail"]
    assert by["sshdir"]["kind"] == "symlink" and "userpath" in by["sshdir"]["detail"]


def test_whole_file_is_scanned_not_just_the_head(clean: Path):
    big = clean / "big.log"
    with big.open("w") as f:
        f.write("x" * (3 * 1024 * 1024) + "\nkey AKIA" + "ABCDEFGHIJKLMNOP\n")
    assert ("secret", "big.log") in kinds(clean, max_mb=10)


def test_secret_split_across_a_chunk_boundary_is_found(clean: Path):
    f = clean / "edge.txt"
    pad = pc.CHUNK - 8
    f.write_text("y" * (pad - 1) + "\n" + "AKIA" + "ABCDEFGHIJKLMNOP\n")  # key straddles the boundary
    assert ("secret", "edge.txt") in kinds(clean, max_mb=10)


@pytest.mark.parametrize("magic", [b"\xcf\xfa\xed\xfe", b"\xca\xfe\xba\xbe", b"\x7fELF"])
def test_executables_are_caught_by_header_without_an_extension(clean: Path, magic: bytes):
    (clean / "tool").write_bytes(magic + b"\x00" * 64)
    assert ("binary", "tool") in kinds(clean)


def test_mz_without_a_pe_signature_still_fails_closed(clean: Path):
    (clean / "tool").write_bytes(b"MZ\x90\x00" + b"\x00" * 64)  # not a PE, but not text either
    assert kinds(clean) == {("opaque", "tool")}


@pytest.mark.parametrize("name", ["addon.node", "mod.jar", "A.class"])
def test_more_binary_extensions(clean: Path, name: str):
    (clean / name).write_bytes(b"\x00")
    assert ("binary", name) in kinds(clean)


def test_framework_dir_and_root_bundle(clean: Path, tmp_path: Path):
    (clean / "Bar.framework" / "Versions").mkdir(parents=True)
    assert ("binary", "Bar.framework") in kinds(clean)
    app = tmp_path / "Foo.app"
    (app / "Contents").mkdir(parents=True)
    assert ("binary", ".") in kinds(app)


def test_special_files_are_skipped_not_hung_on(clean: Path):
    os.mkfifo(clean / "fifo")
    assert pc.scan(clean, hostnames=set(), username=None) == []


@pytest.mark.skipif(os.geteuid() == 0, reason="root can read mode-000 files")
def test_unreadable_file_is_exit_2_not_clean(clean: Path):
    f = clean / "locked.txt"
    f.write_text("x")
    f.chmod(0)
    try:
        with pytest.raises(pc.Unreadable):
            pc.scan(clean, hostnames=set(), username=None)
        r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
        assert r.returncode == 2 and "cannot read" in r.stderr
    finally:
        f.chmod(_stat.S_IRUSR | _stat.S_IWUSR)


def test_utf16_text_is_scanned(clean: Path):
    (clean / "notes.txt").write_bytes("token ghp_".encode("utf-16") + ("a" * 36).encode("utf-16-le"))
    assert ("secret", "notes.txt") in kinds(clean)


@pytest.mark.parametrize("text,kind", [
    ("vault: ~/alice-vault/notes", "userpath"),
    ("path ~/projects/alice/x", "userpath"),
    ("author: alice", "username"),
])
def test_login_name_in_tilde_paths_and_text(clean: Path, text: str, kind: str):
    (clean / "doc.md").write_text(text + "\n")
    assert (kind, "doc.md") in kinds(clean, username="alice")


def test_login_name_is_matched_as_a_word(clean: Path):
    (clean / "doc.md").write_text("malice and alicea are other words\n")
    assert kinds(clean, username="alice") == set()


def test_deny_terms(clean: Path, tmp_path: Path):
    (clean / "doc.md").write_text("see concept/project-falcon for the claim\n")
    assert ("denied", "doc.md") in kinds(clean, deny=["project-falcon"])
    deny = tmp_path / "deny.txt"
    deny.write_text("# private slugs\nproject-falcon\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--deny-file", str(deny)],
                       capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK denied" in r.stdout


def test_skipped_dirs_are_listed_for_review(clean: Path):
    (clean / "node_modules" / "x").mkdir(parents=True)
    assert pc.skipped_dirs(clean) == ["node_modules"]
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert "REVIEW skipped  node_modules" in r.stdout


# --- added after P20 round 2 (BRO-2816): fail closed on what the scan cannot read --------

@pytest.mark.parametrize("name,payload", [
    ("profile.sqlite", b"SQLite format 3\x00" + b"\x00" * 32 + b"/Users/alice/vault"),
    ("leveldb.log", b"\x00\x01" + b"key AKIA" + b"ABCDEFGHIJKLMNOP"),
    ("blob.dat", b"\x00\x00\x00\x01\x02"),
])
def test_unrecognised_binaries_fail_closed_and_are_strings_scanned(clean: Path, name: str, payload: bytes):
    (clean / name).write_bytes(payload)
    found = kinds(clean)
    assert ("opaque", name) in found
    if b"/Users/alice" in payload:
        assert ("userpath", name) in found
    if b"AKIA" in payload:
        assert ("secret", name) in found
    assert ("opaque", name) not in kinds(clean, allow=[name])


@pytest.mark.parametrize("name", ["session.har", "dump.pcapng", "bt.pklg", "hci.btsnoop"])
def test_captures_block(clean: Path, name: str):
    (clean / name).write_text("{}\n")
    assert ("capture", name) in kinds(clean)


@pytest.mark.parametrize("text", [
    'Authorization: Bearer abcdefghijklmnop.qrs',
    '"authorization": "Bearer abcdefghijklmnopqrst"',
    "token=" + "eyJ" + "hbGciOiJub25lIn0" + "." + "eyJ" + "zdWIiOiJ0ZXN0In0" + "." + "c2lnbmF0dXJlLXRlc3Q",  # assembled at runtime: no literal token in source
    "Cookie: session=abcdef123456",
    '  "set-cookie": "sid=0123456789abcdef; Path=/"',
])
def test_session_tokens_block(clean: Path, text: str):
    (clean / "evidence.txt").write_text(text + "\n")
    assert ("secret", "evidence.txt") in kinds(clean)


def test_names_are_scanned_like_contents(clean: Path):
    (clean / "alice-vault").mkdir()
    (clean / "alice-vault" / "a.txt").write_text("clean\n")
    (clean / "Bob-MacBook-Pro").mkdir()
    (clean / "Bob-MacBook-Pro" / "b.txt").write_text("clean\n")
    (clean / "projectx-notes.md").write_text("clean\n")
    found = kinds(clean, username="alice", deny=["projectx"])
    assert ("username", "alice-vault") in found or ("userpath", "alice-vault") in found
    assert ("hostname", "Bob-MacBook-Pro") in found
    assert ("denied", "projectx-notes.md") in found


def test_mz_text_is_not_a_pe_file(clean: Path):
    (clean / "README.md").write_text("MZ-1 drum machine notes\n")
    (clean / "codes.csv").write_text("MZA,Mozambique\n")
    assert kinds(clean) == set()


def test_real_pe_header_is_caught(clean: Path):
    head = bytearray(b"MZ" + b"\x00" * 0x3A + (0x80).to_bytes(4, "little") + b"\x00" * (0x80 - 0x40) + b"PE\x00\x00")
    (clean / "tool").write_bytes(bytes(head) + b"\x00" * 64)
    assert ("binary", "tool") in kinds(clean)


def test_utf16be_beyond_the_first_chunk(clean: Path):
    body = "x" * (pc.CHUNK // 2 + 100) + "\ntoken ghp_" + "a" * 36 + "\n"
    (clean / "big16.txt").write_bytes(b"\xfe\xff" + body.encode("utf-16-be"))
    assert ("secret", "big16.txt") in kinds(clean, max_mb=20)


def test_generic_container_logins_are_not_matched():
    assert all(u not in pc.GENERIC_LOGINS for u in [pc.local_username()] if u)
    assert {"node", "vscode", "test", "build", "code"} <= pc.GENERIC_LOGINS


def test_deny_terms_are_unicode_normalized_and_hash_can_be_escaped(clean: Path, tmp_path: Path):
    (clean / "doc.md").write_text("by Andre\u0301s, tag #falcon\n")
    assert ("denied", "doc.md") in kinds(clean, deny=["Andrés"])
    deny = tmp_path / "deny.txt"
    deny.write_text("# a comment\n\\#falcon\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--deny-file", str(deny)],
                       capture_output=True, text=True)
    assert r.returncode == 1 and "#falcon" in r.stdout


def test_special_files_are_listed_for_review(clean: Path):
    os.mkfifo(clean / "pipe")
    assert "pipe" in pc.skipped_dirs(clean)
