"""Tests for scripts/publish_check.py — what must never leave the machine."""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "publish_check.py"
spec = importlib.util.spec_from_file_location("publish_check", SCRIPT)
pc = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pc)


def kinds(root: Path, **kw) -> set[tuple[str, str]]:
    kw.setdefault("hostnames", set())
    kw.setdefault("username", None)
    return {(f["kind"], f["path"]) for f in pc.scan(root, **kw)}


@pytest.fixture
def clean(tmp_path: Path) -> Path:
    (tmp_path / "main.js").write_text("module.exports = class Plugin {}\n")
    (tmp_path / "manifest.json").write_text('{"id": "x"}\n')
    (tmp_path / "README.md").write_text("Install into <vault>/.obsidian/plugins/x\n")
    return tmp_path


def test_clean_mod_passes(clean: Path):
    assert pc.scan(clean) == []
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 0 and r.stdout.startswith("OK")


@pytest.mark.parametrize("name", ["app.asar", "libfoo.dylib", "game.z64", "data.pak"])
def test_third_party_binaries_block(clean: Path, name: str):
    (clean / name).write_bytes(b"\x00\x01")
    assert ("binary", name) in kinds(clean)


def test_app_bundle_directory_blocks_and_is_not_descended(clean: Path):
    (clean / "Target.app" / "Contents").mkdir(parents=True)
    (clean / "Target.app" / "Contents" / "x.dylib").write_bytes(b"\x00")
    found = kinds(clean)
    assert ("binary", "Target.app") in found
    assert not any(p.startswith("Target.app/") for _, p in found)


def test_allow_glob_exempts(clean: Path):
    (clean / "assets").mkdir()
    (clean / "assets" / "own.bin").write_bytes(b"\x00")
    assert ("binary", "assets/own.bin") in kinds(clean)
    assert ("binary", "assets/own.bin") not in kinds(clean, allow=["assets/*.bin"])


def test_large_file_blocks(clean: Path):
    (clean / "big.txt").write_bytes(b"a" * (2 * 1024 * 1024))
    assert ("large", "big.txt") in kinds(clean, max_mb=1)
    assert ("large", "big.txt") not in kinds(clean, max_mb=5)


@pytest.mark.parametrize("text", [
    "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n",
    "key = AKIA" + "ABCDEFGHIJKLMNOP\n",
    "token: ghp_" + "a" * 36 + "\n",
    "SLACK=xoxb-" + "1234567890-abcdef\n",
    "OPENAI=sk-" + "a" * 24 + "\n",
])
def test_secrets_block(clean: Path, text: str):
    (clean / "config.js").write_text(text)
    assert ("secret", "config.js") in kinds(clean)


@pytest.mark.parametrize("header", [
    "// Decompiled with JetBrains decompiler\n",
    "// Generated by Ghidra\n",
    "/* jadx */\n",
    "// ILSpy output\n",
])
def test_decompiler_output_blocks(clean: Path, header: str):
    (clean / "Lifted.java").write_text(header + "class A {}\n")
    assert ("decomp", "Lifted.java") in kinds(clean)


@pytest.mark.parametrize("text,blocks", [
    ("path = '/Users/alice/Library/x'", True),
    ("path = '/home/bob/.config'", True),
    (r"path = 'C:\Users\carol\AppData'", True),
    ("path = '/Users/Shared/x'", False),
    ("path = '~/Library/x'", False),
])
def test_user_paths(clean: Path, text: str, blocks: bool):
    (clean / "paths.py").write_text(text + "\n")
    assert (("userpath", "paths.py") in kinds(clean)) is blocks


def test_dependency_and_vcs_folders_block_and_are_not_entered(clean: Path):
    (clean / "node_modules" / "dep").mkdir(parents=True)
    (clean / "node_modules" / "dep" / "lib.dylib").write_bytes(b"\x00")
    (clean / ".git").mkdir()
    (clean / ".git" / "secret").write_text("ghp_" + "a" * 36)
    assert kinds(clean) == {("folder", "node_modules"), ("folder", ".git")}


def test_binary_content_is_strings_scanned(clean: Path):
    # An image's metadata can carry a path; the scan reads printable runs of binary files.
    (clean / "icon.png").write_bytes(b"\x89PNG\x00" + b"/Users/alice/" )
    assert ("userpath", "icon.png") in kinds(clean)


def test_cli_exit_codes(clean: Path, tmp_path: Path):
    (clean / "x.dll").write_bytes(b"\x00")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK binary" in r.stdout
    r = subprocess.run([sys.executable, str(SCRIPT), str(tmp_path / "nope")], capture_output=True, text=True)
    assert r.returncode == 2


# --- added after the first dogfood run (BRO-2816 friction report) -------------------

@pytest.mark.parametrize("text", [
    "lock: Janes-MacBook-Pro.local-52658",
    "host=Bob-Mac-mini.local",
    "SingletonLock -> Ana-MacBook-Air-2",
])
def test_mac_style_hostnames_block(clean: Path, text: str):
    (clean / "lab.log").write_text(text + "\n")
    assert ("hostname", "lab.log") in kinds(clean, hostnames=set())


def test_this_machines_hostname_blocks(clean: Path):
    (clean / "lab.log").write_text("pid 4242 on studio-workstation-7\n")
    assert ("hostname", "lab.log") in kinds(clean, hostnames={"studio-workstation-7"})
    assert ("hostname", "lab.log") not in kinds(clean, hostnames=set())


def test_short_generic_hostnames_are_not_matched():
    assert all(len(h) >= 6 for h in pc.local_hostnames())
    assert "localhost" not in pc.local_hostnames()


def test_images_are_listed_for_review_not_blocked(clean: Path):
    (clean / "evidence").mkdir()
    (clean / "evidence" / "shot.png").write_bytes(b"\x89PNG\x00")
    assert pc.scan(clean, hostnames=set(), username=None) == []
    assert pc.review_images(clean) == ["evidence/shot.png"]
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 0 and "REVIEW image    evidence/shot.png" in r.stdout


# --- added after P20 round 1 (BRO-2816) ---------------------------------------------

import os
import stat as _stat


def test_symlinked_file_and_dir_are_findings_with_their_target(clean: Path, tmp_path: Path):
    (clean / "secret.txt").write_text("nothing\n")
    os.symlink("../outside/key", clean / "key")
    os.symlink("/Users/alice/.ssh", clean / "sshdir")
    found = pc.scan(clean, hostnames=set(), username=None)
    kinds_at = lambda path: {f["kind"] for f in found if f["path"] == path}  # noqa: E731
    assert kinds_at("key") == {"symlink"}
    assert any("../outside/key" in f["detail"] for f in found if f["path"] == "key")
    assert kinds_at("sshdir") == {"symlink", "userpath"}  # the leaking target is its own finding


def test_whole_file_is_scanned_not_just_the_head(clean: Path):
    big = clean / "big.log"
    with big.open("w") as f:
        f.write("x" * (3 * 1024 * 1024) + "\nkey AKIA" + "ABCDEFGHIJKLMNOP\n")
    assert ("secret", "big.log") in kinds(clean, max_mb=10)


def test_secret_split_across_a_chunk_boundary_is_found(clean: Path):
    f = clean / "edge.txt"
    pad = pc.CHUNK - 8
    f.write_text("y" * (pad - 1) + "\n" + "AKIA" + "ABCDEFGHIJKLMNOP\n")  # key straddles the boundary
    assert ("secret", "edge.txt") in kinds(clean, max_mb=10)


@pytest.mark.parametrize("magic", [b"\xcf\xfa\xed\xfe", b"\xca\xfe\xba\xbe", b"\x7fELF"])
def test_executables_are_caught_by_header_without_an_extension(clean: Path, magic: bytes):
    (clean / "tool").write_bytes(magic + b"\x00" * 64)
    assert ("binary", "tool") in kinds(clean)


def test_mz_without_a_pe_signature_still_fails_closed(clean: Path):
    (clean / "tool").write_bytes(b"MZ\x90\x00" + b"\x00" * 64)  # not a PE, and not a shippable type
    assert kinds(clean) == {("type", "tool")}
    (clean / "tool").rename(clean / "tool.txt")                   # a text type that is not text
    assert kinds(clean) == {("opaque", "tool.txt")}


@pytest.mark.parametrize("name", ["addon.node", "mod.jar", "A.class"])
def test_more_binary_extensions(clean: Path, name: str):
    (clean / name).write_bytes(b"\x00")
    assert ("binary", name) in kinds(clean)


def test_framework_dir_and_root_bundle(clean: Path, tmp_path: Path):
    (clean / "Bar.framework" / "Versions").mkdir(parents=True)
    assert ("binary", "Bar.framework") in kinds(clean)
    app = tmp_path / "Foo.app"
    (app / "Contents").mkdir(parents=True)
    assert ("binary", ".") in kinds(app)


def test_special_files_are_skipped_not_hung_on(clean: Path):
    os.mkfifo(clean / "fifo")
    assert pc.scan(clean, hostnames=set(), username=None) == []


@pytest.mark.skipif(os.geteuid() == 0, reason="root can read mode-000 files")
def test_unreadable_file_is_exit_2_not_clean(clean: Path):
    f = clean / "locked.txt"
    f.write_text("x")
    f.chmod(0)
    try:
        with pytest.raises(pc.Unreadable):
            pc.scan(clean, hostnames=set(), username=None)
        r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
        assert r.returncode == 2 and "cannot read" in r.stderr
    finally:
        f.chmod(_stat.S_IRUSR | _stat.S_IWUSR)


def test_utf16_text_is_scanned(clean: Path):
    (clean / "notes.txt").write_bytes("token ghp_".encode("utf-16") + ("a" * 36).encode("utf-16-le"))
    assert ("secret", "notes.txt") in kinds(clean)


@pytest.mark.parametrize("text,kind", [
    ("vault: ~/alice-vault/notes", "userpath"),
    ("path ~/projects/alice/x", "userpath"),
    ("author: alice", "username"),
])
def test_login_name_in_tilde_paths_and_text(clean: Path, text: str, kind: str):
    (clean / "doc.md").write_text(text + "\n")
    assert (kind, "doc.md") in kinds(clean, username="alice")


def test_login_name_is_matched_as_a_word(clean: Path):
    (clean / "doc.md").write_text("malice and alicea are other words\n")
    assert kinds(clean, username="alice") == set()


def test_deny_terms(clean: Path, tmp_path: Path):
    (clean / "doc.md").write_text("see concept/project-falcon for the claim\n")
    assert ("denied", "doc.md") in kinds(clean, deny=["project-falcon"])
    deny = tmp_path / "deny.txt"
    deny.write_text("# private slugs\nproject-falcon\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--deny-file", str(deny)],
                       capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK denied" in r.stdout


def test_a_venv_inside_the_tree_blocks_even_though_it_is_not_scanned(clean: Path):
    # Round 3: a secret inside a skipped venv/ was reported "not scanned" and exited 0.
    (clean / "m" / "venv").mkdir(parents=True)
    (clean / "m" / "venv" / "notes.txt").write_text("key = AKIA" + "ABCDEFGHIJKLMNOP\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--no-gitleaks"], capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK folder   m/venv" in r.stdout, r.stdout


# --- added after P20 round 2 (BRO-2816): fail closed on what the scan cannot read --------

@pytest.mark.parametrize("name,payload", [
    ("profile.sqlite", b"SQLite format 3\x00" + b"\x00" * 32 + b"/Users/alice/vault"),
    ("leveldb.log", b"\x00\x01" + b"key AKIA" + b"ABCDEFGHIJKLMNOP"),
    ("blob.dat", b"\x00\x00\x00\x01\x02"),
])
def test_unrecognised_binaries_fail_closed_and_are_strings_scanned(clean: Path, name: str, payload: bytes):
    (clean / name).write_bytes(payload)
    found = kinds(clean)
    # Not a shippable type at all (type), or a text type whose bytes are not text (opaque).
    kind = "opaque" if Path(name).suffix in pc.SHIP_TEXT_EXT else "type"
    assert (kind, name) in found
    if b"/Users/alice" in payload:
        assert ("userpath", name) in found
    if b"AKIA" in payload:
        assert ("secret", name) in found
    assert (kind, name) not in kinds(clean, allow=[name])


@pytest.mark.parametrize("name", ["session.har", "dump.pcapng", "bt.pklg", "hci.btsnoop"])
def test_captures_block(clean: Path, name: str):
    (clean / name).write_text("{}\n")
    assert ("capture", name) in kinds(clean)


@pytest.mark.parametrize("text", [
    'Authorization: Bearer abcdefghijklmnop.qrs',
    '"authorization": "Bearer abcdefghijklmnopqrst"',
    "token=" + "eyJ" + "hbGciOiJub25lIn0" + "." + "eyJ" + "zdWIiOiJ0ZXN0In0" + "." + "c2lnbmF0dXJlLXRlc3Q",  # assembled at runtime: no literal token in source
])
def test_session_tokens_block(clean: Path, text: str):
    (clean / "evidence.txt").write_text(text + "\n")
    assert ("secret", "evidence.txt") in kinds(clean)


def test_names_are_scanned_like_contents(clean: Path):
    (clean / "alice-vault").mkdir()
    (clean / "alice-vault" / "a.txt").write_text("clean\n")
    (clean / "Bob-MacBook-Pro").mkdir()
    (clean / "Bob-MacBook-Pro" / "b.txt").write_text("clean\n")
    (clean / "projectx-notes.md").write_text("clean\n")
    found = kinds(clean, username="alice", deny=["projectx"])
    assert ("username", "alice-vault") in found or ("userpath", "alice-vault") in found
    assert ("hostname", "Bob-MacBook-Pro") in found
    assert ("denied", "projectx-notes.md") in found


def test_mz_text_is_not_a_pe_file(clean: Path):
    (clean / "README.md").write_text("MZ-1 drum machine notes\n")
    (clean / "codes.csv").write_text("MZA,Mozambique\n")
    assert kinds(clean) == set()


def test_real_pe_header_is_caught(clean: Path):
    head = bytearray(b"MZ" + b"\x00" * 0x3A + (0x80).to_bytes(4, "little") + b"\x00" * (0x80 - 0x40) + b"PE\x00\x00")
    (clean / "tool").write_bytes(bytes(head) + b"\x00" * 64)
    assert ("binary", "tool") in kinds(clean)


def test_utf16be_beyond_the_first_chunk(clean: Path):
    body = "x" * (pc.CHUNK // 2 + 100) + "\ntoken ghp_" + "a" * 36 + "\n"
    (clean / "big16.txt").write_bytes(b"\xfe\xff" + body.encode("utf-16-be"))
    assert ("secret", "big16.txt") in kinds(clean, max_mb=20)


def test_generic_container_logins_are_not_matched():
    assert all(u not in pc.GENERIC_LOGINS for u in [pc.local_username()] if u)
    assert {"node", "vscode", "test", "build", "code"} <= pc.GENERIC_LOGINS


def test_deny_terms_are_unicode_normalized_and_hash_can_be_escaped(clean: Path, tmp_path: Path):
    (clean / "doc.md").write_text("by Andre\u0301s, tag #falcon\n")
    assert ("denied", "doc.md") in kinds(clean, deny=["Andrés"])
    deny = tmp_path / "deny.txt"
    deny.write_text("# a comment\n\\#falcon\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--deny-file", str(deny)],
                       capture_output=True, text=True)
    assert r.returncode == 1 and "#falcon" in r.stdout


def test_special_files_are_listed_for_review(clean: Path):
    os.mkfifo(clean / "pipe")
    assert "pipe" in pc.special_files(clean)


# --- the structural reshape (P20 continuation: hoist the invariant) ---------------------

import shutil as _shutil


def test_allow_clears_the_file_finding_but_not_its_content(clean: Path):
    (clean / "state.db").write_bytes(b"SQLite format 3\x00" + b"\x00" * 16 + b" AKIA" + b"ABCDEFGHIJKLMNOP /Users/alice/x")
    rep = pc.scan_report(clean, allow=["state.db"], hostnames=set(), username=None, use_gitleaks=False)
    found = {(f["kind"], f["path"]) for f in rep["findings"]}
    assert ("type", "state.db") in kinds(clean)         # blocked before the allow
    assert ("type", "state.db") not in found            # cleared as a file
    assert ("secret", "state.db") in found and ("userpath", "state.db") in found  # content still scanned
    assert rep["allowed"] == ["state.db"]
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--allow", "state.db", "--no-gitleaks"],
                       capture_output=True, text=True)
    assert r.returncode == 1 and "REVIEW allowed  state.db" in r.stdout


def test_allowed_images_stay_on_the_review_list(clean: Path):
    (clean / "shot.png").write_bytes(b"\x89PNG\x00")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--allow", "*.png", "--no-gitleaks"],
                       capture_output=True, text=True)
    assert "REVIEW image    shot.png" in r.stdout


def test_ds_store_is_blocked_with_a_remedy(clean: Path):
    (clean / ".DS_Store").write_bytes(b"\x00\x00\x00\x01Bud1")
    found = pc.scan(clean, hostnames=set(), username=None)
    assert any(f["kind"] == "opaque" and f["path"] == ".DS_Store" and "delete it" in f["detail"] for f in found)


def test_the_root_folders_own_name_is_scanned(tmp_path: Path):
    root = tmp_path / "alice-vault-plugin"
    root.mkdir()
    (root / "main.js").write_text("ok\n")
    assert any(f["path"] == "." for f in pc.scan(root, hostnames=set(), username="alice"))


@pytest.mark.skipif(not _shutil.which("gitleaks"), reason="gitleaks not installed")
def test_gitleaks_findings_are_reported_without_the_secret(clean: Path):
    import random, string
    rnd = random.Random(7)  # seeded: a realistic-entropy token, assembled at runtime
    tok = "ghp_" + "".join(rnd.choice(string.ascii_letters + string.digits) for _ in range(36))
    (clean / "config.js").write_text(f'const t = "{tok}";\n')
    rep = pc.scan_report(clean, hostnames=set(), username=None, use_gitleaks=True)
    assert rep["secrets_engine"].startswith("gitleaks")
    gl = [f for f in rep["findings"] if f["detail"].startswith("gitleaks")]
    assert gl and all(tok not in f["detail"] for f in gl)


def test_missing_gitleaks_is_announced_as_partial(clean: Path, tmp_path: Path):
    empty = tmp_path / "emptybin"
    empty.mkdir()
    # HOME must not be the scanned folder: some Pythons write a bytecode cache under it.
    home = Path(tempfile.mkdtemp(prefix="pc-home."))
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True,
                       env={"PATH": str(empty), "HOME": str(home)})
    assert r.returncode == 0 and "REVIEW secrets  PARTIAL: gitleaks is not installed" in r.stdout


# --- fresh round 1 after the reshape (BRO-2816) -----------------------------------------

import sqlite3 as _sqlite3


def _rand_token(prefix: str, n: int, seed: int = 7) -> str:
    import random, string
    rnd = random.Random(seed)
    return prefix + "".join(rnd.choice(string.ascii_letters + string.digits) for _ in range(n))


def test_token_packed_in_a_real_sqlite_row_is_found_even_when_allowed(clean: Path):
    db = clean / "store.sqlite"
    con = _sqlite3.connect(db)
    con.execute("create table k (svc text, val text)")
    con.execute("insert into k values (?, ?)", ("github", _rand_token("ghp_", 36)))
    con.commit(); con.close()
    rep = pc.scan_report(clean, allow=["*.sqlite"], hostnames=set(), username=None, use_gitleaks=False)
    assert ("secret", "store.sqlite") in {(f["kind"], f["path"]) for f in rep["findings"]}


def test_allow_does_not_clear_what_a_ds_store_or_a_link_target_leaks(clean: Path):
    (clean / "assets").mkdir()
    (clean / "assets" / ".DS_Store").write_bytes(b"\x00\x00\x00\x01Bud1/Users/alice/secret-project")
    os.symlink("/Users/alice/private/notes.md", clean / "link.md")
    rep = pc.scan_report(clean, allow=["assets", "link.md"], hostnames=set(), username=None, use_gitleaks=False)
    found = {(f["kind"], f["path"]) for f in rep["findings"]}
    assert ("userpath", "assets/.DS_Store") in found and ("opaque", "assets/.DS_Store") not in found
    assert ("userpath", "link.md") in found and ("symlink", "link.md") not in found


def test_an_in_tree_gitleaks_config_or_ignore_file_is_blocked(clean: Path):
    (clean / ".gitleaks.toml").write_text("[allowlist]\npaths = ['.*']\n")
    (clean / "sub").mkdir()
    (clean / "sub" / ".gitleaksignore").write_text("cfg.py:gitlab-pat:1\n")
    found = kinds(clean)
    assert ("gitleaks", ".gitleaks.toml") in found and ("gitleaks", "sub/.gitleaksignore") in found
    # not clearable: --allow is for "is this file shippable", and this file changes what is checked
    assert ("gitleaks", ".gitleaks.toml") in kinds(clean, allow=[".gitleaks.toml"])


@pytest.mark.skipif(not _shutil.which("gitleaks"), reason="gitleaks not installed")
def test_a_real_fingerprint_in_gitleaksignore_cannot_make_the_run_quiet(clean: Path):
    tok = "glpat-" + _rand_token("", 20, seed=5)
    (clean / "cfg.py").write_text(f'T = "{tok}"\n')
    probe = subprocess.run(["gitleaks", "dir", str(clean), "--no-banner", "--exit-code", "0",
                            "--report-format", "json", "--report-path", "-"], capture_output=True, text=True)
    fps = [leak["Fingerprint"] for leak in json.loads(probe.stdout or "[]")]
    assert fps, "the probe token should be a gitleaks finding"
    (clean / ".gitleaksignore").write_text("\n".join(fps) + "\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK gitleaks .gitleaksignore" in r.stdout


def test_evidence_files_are_listed_for_review(clean: Path):
    (clean / "evidence").mkdir()
    (clean / "evidence" / "dom.txt").write_text("page text\n")
    (clean / "evidence" / "shot.png").write_bytes(b"\x89PNG\x00")
    assert ("evidence", "evidence/dom.txt") in pc.review_extra(clean)
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--no-gitleaks"], capture_output=True, text=True)
    assert "REVIEW evidence evidence/dom.txt" in r.stdout


def test_home_path_without_a_trailing_slash(clean: Path):
    (clean / "cfg.json").write_text('{"cwd": "/Users/alice"}\n')
    assert ("userpath", "cfg.json") in kinds(clean)


@pytest.mark.skipif(os.geteuid() == 0, reason="root can read mode-000 folders")
def test_unreadable_subfolder_is_exit_2(clean: Path):
    sub = clean / "locked"
    sub.mkdir()
    (sub / "x.txt").write_text("x")
    sub.chmod(0)
    try:
        r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--no-gitleaks"], capture_output=True, text=True)
        assert r.returncode == 2 and "cannot read" in r.stderr
    finally:
        sub.chmod(0o755)


@pytest.mark.parametrize("value", ["nan", "-1", "0", "inf"])
def test_max_mb_must_be_a_positive_number(clean: Path, value: str):
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--max-mb", value], capture_output=True, text=True)
    assert r.returncode == 2


def test_an_image_extension_on_a_non_image_is_opaque(clean: Path):
    (clean / "photo.png").write_bytes(b"SQLite format 3\x00" + b"\x00" * 32)
    assert ("opaque", "photo.png") in kinds(clean)


def test_token_split_across_binary_chunks_is_found(clean: Path):
    tok = _rand_token("ghp_", 36, seed=3)
    f = clean / "blob.bin"
    pad = pc.CHUNK - 10
    f.write_bytes(b"\x00" * pad + tok.encode() + b"\x00" * 16)
    rep = pc.scan_report(clean, allow=["blob.bin"], max_mb=10, hostnames=set(), username=None, use_gitleaks=False)
    assert ("secret", "blob.bin") in {(x["kind"], x["path"]) for x in rep["findings"]}


def test_a_single_file_can_be_checked(clean: Path, tmp_path: Path):
    note = tmp_path / "field-note.md"
    note.write_text("vault at ~/Documents/AcmeSecretVault\n")
    deny = tmp_path / "deny.txt"
    deny.write_text("AcmeSecretVault\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(note), "--deny-file", str(deny), "--no-gitleaks"],
                       capture_output=True, text=True)
    assert r.returncode == 1 and f"BLOCK denied   {note}" in r.stdout


def test_fine_grained_github_token_is_a_built_in_shape(clean: Path):
    (clean / "env.txt").write_text("T=" + _rand_token("github_pat_", 40) + "\n")
    assert ("secret", "env.txt") in kinds(clean)


def test_no_gitleaks_flag_is_announced_as_partial(clean: Path):
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--no-gitleaks"], capture_output=True, text=True)
    assert "REVIEW secrets  PARTIAL: gitleaks was not run (--no-gitleaks)" in r.stdout


def test_a_dotfile_under_a_home_dir_is_not_a_username(clean: Path):
    (clean / "lab.py").write_text("# binds <lab>/home/.obsidian-cli.sock\n")
    assert kinds(clean) == set()


# --- fresh round 2 (BRO-2816) -------------------------------------------------------------

def test_aws_key_packed_in_a_real_sqlite_row(clean: Path):
    db = clean / "keys.sqlite"
    con = _sqlite3.connect(db)
    con.execute("create table k (id text, secret text)")
    con.execute("insert into k values (?, ?)", ("AKIA" + "IOSFODNN7EXAMPLQ", "nextvalue"))
    con.commit(); con.close()
    rep = pc.scan_report(clean, allow=["*.sqlite"], hostnames=set(), username=None, use_gitleaks=False)
    assert ("secret", "keys.sqlite") in {(f["kind"], f["path"]) for f in rep["findings"]}


def test_sk_shape_stays_anchored_in_binaries(clean: Path):
    (clean / "chart.png").write_bytes(b"\x89PNG\r\n\x1a\n" + b"tEXt" + b"risk-assessment-for-the-project-2026")
    assert kinds(clean) == set()


@pytest.mark.skipif(os.geteuid() == 0, reason="root reads mode-000 files")
def test_single_file_unreadable_is_exit_2(tmp_path: Path):
    f = tmp_path / "note.md"
    f.write_text("x")
    f.chmod(0)
    try:
        r = subprocess.run([sys.executable, str(SCRIPT), str(f), "--no-gitleaks"], capture_output=True, text=True)
        assert r.returncode == 2 and "cannot read" in r.stderr
    finally:
        f.chmod(0o644)


def test_single_file_symlink_is_blocked_not_followed(tmp_path: Path):
    (tmp_path / "real.md").write_text("clean\n")
    link = tmp_path / "note.md"
    os.symlink(tmp_path / "real.md", link)
    r = subprocess.run([sys.executable, str(SCRIPT), str(link), "--no-gitleaks"], capture_output=True, text=True)
    assert r.returncode == 1 and "BLOCK symlink" in r.stdout


def test_single_file_under_evidence_is_reviewed(tmp_path: Path):
    (tmp_path / "evidence").mkdir()
    f = tmp_path / "evidence" / "dom.txt"
    f.write_text("page\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(f), "--no-gitleaks"], capture_output=True, text=True)
    assert "REVIEW evidence" in r.stdout


@pytest.mark.parametrize("name,head,real", [
    ("a.tiff", b"II*\x00" + b"\x00" * 16, True),
    ("b.tiff", b"SQLite format 3\x00", False),
    ("c.webp", b"RIFF\x00\x00\x00\x00WEBP", True),
    ("d.webp", b"RIFF\x00\x00\x00\x00WAVE", False),
    ("e.heic", b"\x00\x00\x00\x18ftypheic", True),
    ("f.heic", b"\x00\x00\x00\x00", False),
])
def test_more_image_headers_are_checked(clean: Path, name: str, head: bytes, real: bool):
    (clean / name).write_bytes(head + b"\x00" * 32)
    assert (("opaque", name) in kinds(clean)) is (not real)


def test_fixture_files_are_listed_for_review(clean: Path):
    (clean / "harness" / "fixtures").mkdir(parents=True)
    (clean / "harness" / "fixtures" / "recorded.json").write_text("{}\n")
    assert ("fixtures", "harness/fixtures/recorded.json") in pc.review_extra(clean)


def test_installed_but_failing_gitleaks_is_exit_2(clean: Path, tmp_path: Path):
    bindir = tmp_path / "fakebin"
    bindir.mkdir()
    fake = bindir / "gitleaks"
    fake.write_text("#!/bin/sh\necho broken >&2\nexit 3\n")
    fake.chmod(0o755)
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean)], capture_output=True, text=True,
                       env={"PATH": f"{bindir}:/usr/bin:/bin", "HOME": str(tmp_path)})
    assert r.returncode == 2 and "gitleaks is installed but" in r.stderr


def test_the_strings_pass_keeps_the_word_boundary_on_the_generic_sk_shape():
    # Unanchored, "sk-" plus 20 word characters matches ordinary text inside an image's
    # metadata; the other shapes have distinctive prefixes and drop the boundary safely.
    prose = "risk-assessment-for-the-quarterly-report"
    assert not [f for f in pc._text_findings("x.png", prose, set(), None, [], loose=True)
                if f["kind"] == "secret"]
    key = "sk-" + "A1b2C3d4E5f6G7h8J9k0L1m2"
    assert [f for f in pc._text_findings("x.png", f"\x00{key}\x00", set(), None, [], loose=True)
            if f["kind"] == "secret"]


# --- P20 round 3 (BRO-2820): a ship allowlist instead of a NUL sniff ----------------------

def test_a_pdf_is_not_on_the_ship_allowlist_even_when_it_looks_like_text(clean: Path):
    # 9 of 40 system PDFs had no NUL in their first 8 KB, so a sniff read them as text.
    (clean / "report.pdf").write_bytes(b"%PDF-1.4\n" + b"x" * 9000 + b"\n%%EOF\n")
    assert kinds(clean) == {("type", "report.pdf")}


def test_a_text_type_must_decode_as_text_all_the_way_through(clean: Path):
    import zlib
    blob = zlib.compress(b"/Users/alice/vault AKIA" + b"ABCDEFGHIJKLMNOP" * 4, 9)
    (clean / "notes.txt").write_bytes(b"plain text header\n" * 600 + blob)  # > 8 KB of text first
    assert ("opaque", "notes.txt") in kinds(clean)


@pytest.mark.parametrize("name", ["LICENSE", "NOTICE", "Makefile", ".gitignore", "README-ja", "main.js",
                                  "patch.diff", "manifest.json", "style.css"])
def test_ordinary_mod_files_ship(clean: Path, name: str):
    (clean / name).write_text("hello\n")
    assert kinds(clean) == set()


@pytest.mark.parametrize("name", ["font.ttf", "song.mp3", "archive.zip", "data", "notes.docx"])
def test_other_types_block_until_allowed(clean: Path, name: str):
    (clean / name).write_bytes(b"hello\n")
    assert kinds(clean) == {("type", name)}
    assert kinds(clean, allow=[name]) == set()


def test_a_deny_term_is_found_across_a_line_wrap(clean: Path):
    (clean / "note.md").write_text("Thanks to Ada\n  Lovelace for the idea.\n")
    assert ("denied", "note.md") in kinds(clean, deny=["Ada Lovelace"])


def test_a_bearer_token_without_a_colon_is_a_secret(clean: Path):
    (clean / "u.user.js").write_text('xhr.setRequestHeader("Authorization", "Bearer 9f8e7d6c5b4a39281706f5e4d3c2b1a0");\n')
    assert ("secret", "u.user.js") in kinds(clean)
    (clean / "u.user.js").write_text("Bearer tokens are sent in a header.\n")
    assert ("secret", "u.user.js") not in kinds(clean)


@pytest.mark.parametrize("offset", [0, 1])
def test_utf16_text_in_an_image_is_found_at_either_alignment(clean: Path, offset: int):
    png = b"\x89PNG\r\n\x1a\n" + b"\x01" * offset + "/Users/alice/Research".encode("utf-16-le")
    (clean / "shot.png").write_bytes(png)
    assert ("userpath", "shot.png") in kinds(clean)


def test_hardware_addresses_block_except_the_documentation_range(clean: Path):
    (clean / "lamp.py").write_text('ADDR = "C4:7C:8D:6A:1B:2E"\n')
    assert ("address", "lamp.py") in kinds(clean)
    (clean / "lamp.py").write_text('ADDR = "00:00:5E:00:53:01"  # RFC 7042 documentation address\n')
    assert ("address", "lamp.py") not in kinds(clean)


@pytest.mark.parametrize("text", ["/var/folders/g9/_dhv_jzj5ljd5nywv14y31hm0000gn/T/tmp.x/evidence",
                                  "cd /root/.config/app"])
def test_macos_temp_and_root_home_paths_are_userpaths(clean: Path, text: str):
    (clean / "run.log").write_text(text + "\n")
    assert ("userpath", "run.log") in kinds(clean)


def test_journals_are_listed_for_review(clean: Path):
    (clean / "MODLOG.md").write_text("# journal\n")
    (clean / ".modlog.json").write_text("{}\n")
    assert pc.review_extra(clean) == [("journal", ".modlog.json"), ("journal", "MODLOG.md")]


@pytest.mark.parametrize("name", ["git-lg.gitconfig", ".bashrc", ".profile", "theme.itermcolors", "keys.reg"])
def test_config_files_a_rung_1_mod_is_made_of_ship(clean: Path, name: str):
    # Dogfood (Codex, 2026-10-05): a git alias snippet was blocked and renamed to .conf.
    (clean / name).write_text("[alias]\n\tlg = log --oneline --graph\n")
    assert kinds(clean) == set()


@pytest.mark.parametrize("name", [".env", "prod.env"])
def test_env_files_still_block(clean: Path, name: str):
    (clean / name).write_text("API_URL=https://example.test\n")
    assert kinds(clean) == {("type", name)}


# --- P20 round 2 of the fresh ledger (BRO-2820) --------------------------------------------

@pytest.mark.parametrize("name", [".netrc", ".npmrc", ".pypirc", ".envrc", ".yarnrc", ".git-credentials"])
def test_credential_dotfiles_are_not_on_the_allowlist(clean: Path, name: str):
    (clean / name).write_text("machine api.example.test login ada password Zk3pQ9vLm2Xr7TfB\n")
    assert ("type", name) in kinds(clean)


def test_hardware_addresses_in_names_block(clean: Path):
    (clean / "lamp-A4-C1-38-9F-12-34").mkdir()
    (clean / "lamp-A4-C1-38-9F-12-34" / "notes.md").write_text("hello\n")
    assert ("address", "lamp-A4-C1-38-9F-12-34") in kinds(clean)


def test_svgs_are_listed_with_images(clean: Path):
    (clean / "logo.svg").write_text("<svg/>\n")
    assert pc.review_images(clean) == ["logo.svg"]


def test_build_output_is_scanned_not_blocked(clean: Path):
    (clean / "dist").mkdir()
    (clean / "dist" / "main.js").write_text("console.log(1)\n")
    assert kinds(clean) == set()
    (clean / "dist" / "main.js").write_text('const v = "/Users/alice/vault";\n')
    assert ("userpath", "dist/main.js") in kinds(clean)


def test_help_prints_the_whole_contract():
    r = subprocess.run([sys.executable, str(SCRIPT), "--help"], capture_output=True, text=True)
    assert r.returncode == 0 and "BLOCK (exit 1)" in r.stdout and "NOT detected" in r.stdout
    assert "type/binary/opaque" in r.stdout


def test_ok_line_states_what_it_cannot_see(clean: Path):
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--no-gitleaks"], capture_output=True, text=True)
    assert r.returncode == 0 and "cannot see cookies, sessions or personal data" in r.stdout


def test_text_that_stops_being_text_in_a_later_chunk_is_opaque(clean: Path, monkeypatch):
    monkeypatch.setattr(pc, "CHUNK", 64)  # several chunks, so the failure is not in the first
    (clean / "notes.txt").write_bytes(b"plain text line\n" * 20 + b"\xff\xfe\x00compressed")
    assert ("opaque", "notes.txt") in kinds(clean)


# --- round 3 of the fresh ledger: claim less (BRO-2820) -------------------------------------

def test_encoded_content_is_not_decoded_but_its_carriers_are_reviewed(clean: Path):
    # Each decoder became a new claim to break (one URL-decode pass, \\u for some checks,
    # base64 split at a chunk edge), so the contract is: text is matched as written, and the
    # types that usually embed encoded content are listed for a person.
    (clean / "page.html").write_text('<img src="data:image/png;base64,L1VzZXJzL2FsaWNl">\n')
    (clean / "notes.ipynb").write_text("{}\n")
    (clean / "prefs.plist").write_text("<plist/>\n")
    (clean / "main.js.map").write_text("{}\n")
    assert kinds(clean) == set()
    assert pc.review_extra(clean) == [("encoded", "main.js.map"), ("encoded", "notes.ipynb"),
                                      ("encoded", "page.html"), ("encoded", "prefs.plist")]


@pytest.mark.parametrize("name", [".yarnrc.yml", "pgpass.conf", "credentials.json"])
def test_well_known_credential_names_block_even_with_a_shippable_extension(clean: Path, name: str):
    (clean / name).write_text("npmAuthToken: x\n")
    assert ("credfile", name) in kinds(clean)
    assert ("credfile", name) not in kinds(clean, allow=[name])   # the user looked and allowed it


@pytest.mark.parametrize("name", [".eslintrc", ".babelrc", ".prettierrc"])
def test_js_tool_dotfiles_ship(clean: Path, name: str):
    (clean / name).write_text("{}\n")
    assert kinds(clean) == set()


def test_digit_only_runs_are_not_hardware_addresses(clean: Path):
    (clean / "rec-26-10-05-14-30-59.txt").write_text("at 12:30:45:10:20:30\n")
    assert kinds(clean) == set()


def test_windows_home_paths_match_in_any_case(clean: Path):
    (clean / "run.log").write_text("c:\\users\\ada\\appdata\\x\n")
    assert ("userpath", "run.log") in kinds(clean)


def test_packed_hardware_addresses_in_binary_content_are_found():
    import plistlib
    data = plistlib.dumps({"3c:22:fb:12:34:56": "Lamp"}, fmt=plistlib.FMT_BINARY)
    assert "address" in {f["kind"] for f in pc._strings_findings("bt.plist", data, set(), None, [])}


def test_a_single_encoded_file_is_listed_once(tmp_path: Path):
    page = tmp_path / "page.html"
    page.write_text("<p>hi</p>\n")
    r = subprocess.run([sys.executable, str(SCRIPT), str(page), "--no-gitleaks"], capture_output=True, text=True)
    assert r.stdout.count("REVIEW encoded") == 1, r.stdout


@pytest.mark.parametrize("name", ["notice.npmrc", "readme.env", "application_default_credentials.json"])
def test_known_names_with_credential_suffixes_do_not_ship(clean: Path, name: str):
    (clean / name).write_text("x\n")
    assert kinds(clean) & {("type", name), ("credfile", name)}


# --- round 1 of the round-4 ledger (BRO-2820) ------------------------------------------------

@pytest.mark.parametrize("after", ["date", "data", "unicode"])
def test_addresses_next_to_binary_plist_markers_are_found(after: str):
    import plistlib
    from datetime import datetime
    value = {"date": datetime(2026, 9, 1), "data": b"\x01\x02\x03\x04", "unicode": "Lämp"}[after]
    data = plistlib.dumps({"Address": "3c:22:fb:12:34:56", "Next": value}, fmt=plistlib.FMT_BINARY)
    data2 = plistlib.dumps({"3c:22:fb:12:34:56": value}, fmt=plistlib.FMT_BINARY)
    for blob in (data, data2):
        assert "address" in {f["kind"] for f in pc._strings_findings("bt.plist", blob, set(), None, [])}


def test_one_allow_glob_works_on_the_ship_tree_and_on_the_destination(tmp_path: Path):
    for top in ("ship", "repo/skills/tooling/mod-anything"):
        mod = tmp_path / top / "examples" / "harmony-mod"
        mod.mkdir(parents=True)
        (mod / "Mod.dll").write_bytes(b"MZ" + b"\x00" * 64)
    glob = ["examples/harmony-mod/Mod.dll"]
    ship = tmp_path / "ship"
    dest = tmp_path / "repo/skills/tooling/mod-anything/examples/harmony-mod"
    skill = tmp_path / "repo/skills/tooling/mod-anything"
    assert pc.scan(ship, allow=glob) == []
    assert pc.scan(dest, allow=glob) != []                      # without --base the glob is relative
    assert pc.scan(dest, allow=glob, base=skill) == []          # the re-check: --base at the skill folder
    assert pc.scan(dest, allow=["examples/other/Mod.dll"], base=skill) != []


def test_a_bare_name_glob_does_not_reach_into_subfolders(clean: Path):
    (clean / "evidence" / "vendor").mkdir(parents=True)
    (clean / "evidence" / "vendor" / "Mod.dll").write_bytes(b"MZ" + b"\x00" * 64)
    assert ("binary", "evidence/vendor/Mod.dll") in kinds(clean, allow=["Mod.dll"])


def test_a_credentials_file_is_cleared_only_by_its_own_path(clean: Path):
    (clean / "cfg").mkdir()
    (clean / "cfg" / "pgpass.conf").write_text("db:5432:app:ada:pw\n")
    assert ("credfile", "cfg/pgpass.conf") in kinds(clean, allow=["cfg/*"])
    assert ("credfile", "cfg/pgpass.conf") not in kinds(clean, allow=["cfg/pgpass.conf"])


def test_a_fingerprint_is_not_a_hardware_address(clean: Path):
    (clean / "notes.md").write_text("host key MD5:43:51:43:a1:b5:fc:8b:b7:0a:3a:a9:b1:0f:66:73:a8\n")
    assert kinds(clean) == set()


def test_base_must_be_a_folder(clean: Path):
    r = subprocess.run([sys.executable, str(SCRIPT), str(clean), "--base", str(clean / "nope")],
                       capture_output=True, text=True)
    assert r.returncode == 2 and "--base" in r.stderr


def test_build_output_is_listed_for_review(clean: Path):
    (clean / "dist").mkdir()
    (clean / "dist" / "main.js").write_text("console.log(1)\n")
    assert ("bundle", "dist/main.js") in pc.review_extra(clean)


@pytest.mark.parametrize("blob", [b"\x00LampA3c:22:fb:12:34:56\x00", b"\x00Lamp3c:22:fb:12:34:56D\x00"])
def test_addresses_between_hex_characters_in_binary_content_are_found(blob: bytes):
    assert "address" in {f["kind"] for f in pc._strings_findings("x.bin", blob, set(), None, [])}
